sudo: false
cache:
  - pip
  - npm
  - directories:
    - $HOME/.cache/pip
addons:
  firefox: "latest"
language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install less less-plugin-clean-css grunt-cli
  - export PATH=`pwd`/node_modules/.bin:$PATH
  - ./manage.sh grunt_packages
  - mkdir -p ~/drivers; export PATH=~/drivers:$PATH;
  - GECKODRIVER_URL="https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz";
  - FILE=`mktemp`; wget "$GECKODRIVER_URL" -qO $FILE && tar xz -C ~/drivers -f $FILE geckodriver; rm $FILE; chmod 777 ~/drivers/geckodriver;
install:
  - ./manage.sh update_dev_packages
  - pip install coveralls
script:
  - ./manage.sh styles
  - ./manage.sh grunt_build
  - ./manage.sh tests
after_success:
  - ./manage.sh py_test_coverage
  - coveralls
notifications:
  irc:
    channels:
      - "irc.freenode.org#searx"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
    on_success: change
