os: linux
dist: bionic
language: python
cache:
  - directories:
    - $HOME/.cache/pip
before_cache:
    - sudo chown -R travis:travis $HOME/.cache/pip
    - rm -f $HOME/.cache/pip/log/debug.log
addons:
  firefox: "latest"

install:
  - make V=1 install
  - make V=1 gecko.driver
  - make V=1 node.env
  - make V=1 travis.codecov
script:
  - make V=1 themes
  - make V=1 test
after_success:
  - make V=1 test.coverage
  - codecov

stages:
  - test
  - name: docker
    if: branch = master AND type != pull_request AND env(DOCKER_USERNAME) IS present

jobs:
  include:
    - python: "3.5"
    - python: "3.6"
    - stage: docker
      python: "3.6"
      git:
        depth: false
      services:
        - docker
      addons: []
      before_install: true
      install: true
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make -e GIT_URL=$(git remote get-url origin) docker.push
      after_success: true

notifications:
  irc:
    channels:
      - "irc.freenode.org#searx"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
    on_success: change
