services:
  searxng:
    #image: localhost/searxng/searxng:2025.6.18-506d5cd39
    image: orai-searxng:v1
    volumes:
      - /opt/orai-searxng/searxng:/etc/searxng
        #- /opt/orai-searxng/settings.yml:/etc/searxng/settings.yml
    ports:
      - 8666:8080
    env_file:
      - .env
    networks:
<<<<<<< HEAD
      - distilledstg_backend_net
=======
      - network
>>>>>>> 5e6adfea4f28aff93383e3f7cf63d7498071a93e
    restart: unless-stopped
    env_file:
      - .env

networks:
<<<<<<< HEAD
  distilledstg_backend_net:
    external: true

=======
  network:
    external: true
    name: thesis-staging-network
>>>>>>> 5e6adfea4f28aff93383e3f7cf63d7498071a93e
volumes:
  backend-dbstore:
  uploads:
