services:
  searxng:
    image: localhost/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
      - ./searx:/usr/local/searxng/searx
    ports:
      - 4000:8080
    networks:
      - network
    restart: unless-stopped
    env_file:
      - .env

networks:
  network:
    external: true
    name: thesis-staging-network

volumes:
  backend-dbstore:
  uploads:
