services:
  searxng:
    #image: localhost/searxng/searxng:2025.6.18-506d5cd39
    image: orai-searxng:v1
    volumes:
      - /opt/orai-searxng/searxng:/etc/searxng
        #- /opt/orai-searxng/settings.yml:/etc/searxng/settings.yml
    ports:
      - 8666:8080
    env_file:
      - .env
    networks:
      - network
    restart: unless-stopped

networks:
  network:
    external: true
    name: thesis-staging-network
volumes:
  backend-dbstore:
  uploads:
