services:
  searxng:
    image: localhost/searxng/searxng:2025.6.18-506d5cd39
    volumes:
      - /opt/orai-searxng/searxng:/etc/searxng
        #- /opt/orai-searxng/settings.yml:/etc/searxng/settings.yml
    ports:
      - 8666:8080
    networks:
      - distilledstg_backend_net
    restart: unless-stopped

networks:
  distilledstg_backend_net:
    external: true

volumes:
  backend-dbstore:
  uploads:
