use_default_settings: true

general:
  instance_name: 'searxng'

search:
  autocomplete: 'google'
  formats:
    - html
    - json

server:
  secret_key: 'a2fb23f1b02e6ee83875b09826990de0f6bd908b6638e8c10277d415f6ab852b' # Is overwritten by ${SEARXNG_SECRET}

engines:
  - name: mongodbvector
    engine: mongodbvector
    disabled: false
    mongodb_uri: 'mongodb://root:'
    openai_api_key: 'sk-proj-9As1L0v2y'
    database: 'thesis_dat'
    collection: 'dat'
    collection_vector: 'semantic_question'
    timeout: 10