# Limiter configuration / bot protection & IP rate limitation

[real_ip]

# number of values to trust for X-Forwarded-For
# https://docs.searxng.org/admin/searx.botdetection.html#searx.botdetection.get_real_ip
x_for = 1

[botdetection.ip_limit]

# activate link_token method in the ip_limit method
# https://docs.searxng.org/admin/searx.botdetection.html#method-ip-limit
link_token = true