name: Integration

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  python:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Ubuntu packages
      run: |
        sudo ./utils/searx.sh install packages
        sudo apt install firefox
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Cache Python dependencies
      id: cache-python
      uses: actions/cache@v2
      with:
        path: ./local
        key: python-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements*.txt', 'setup.py') }}
    - name: Install Python dependencies
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: |
        make V=1 install
        make V=1 gecko.driver
    - name: Run tests
      run: make V=1 ci.test
    - name: Test coverage
      run: make V=1 test.coverage
    - name: Store coverage result
      uses: actions/upload-artifact@v2
      with:
        name: coverage-${{ matrix.python-version }}
        path: coverage/
        retention-days: 60

  themes:
    name: Themes
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Ubuntu packages
      run: sudo ./utils/searx.sh install buildhost
    - name: Install node dependencies
      run: make V=1 node.env
    - name: Build themes
      run: make V=1 themes.all

  documentation:
    name: Documentation
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install Ubuntu packages
      run: sudo ./utils/searx.sh install buildhost
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Build documentation
      run: |
        make V=1 docs.clean docs.html
    - name: Deploy
      if:  github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ github.token }}
        BRANCH: gh-pages
        FOLDER: dist/docs
        CLEAN: true # Automatically remove deleted files from the deploy branch
        SINGLE_COMMIT: True
        COMMIT_MESSAGE: build from commit ${{ github.sha }}

  babel:
    name: Babel
    runs-on: ubuntu-20.04
    if: ${{ github.repository_owner == 'searxng' && github.ref == 'refs/heads/master' }}
    needs:
      - python
      - themes
      - documentation
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Update transations
      id: update
      continue-on-error: true
      run: |
        pip install babel jinja2
        searx_extra/update/update_translations.sh
    - name: Open pull request
      if: steps.update.outcome == 'success'
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update translations (pot, po)
        committer: searx-bot <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: update_translations_pot
        delete-branch: true
        draft: false
        title: 'Update translations (pot, po)'
        body: |
          Update messages.pot and messages.po files
        labels: |
          translation

  dockers:
    name: Docker
    if: github.ref == 'refs/heads/master'
    needs:
      - python
      - themes
      - documentation
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        if: env.DOCKERHUB_USERNAME != null
        uses: actions/checkout@v2
        with:
          # make sure "make docker.push" can get the git history
          fetch-depth: '0'
      - name: Set up QEMU
        if: env.DOCKERHUB_USERNAME != null
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: env.DOCKERHUB_USERNAME != null
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: env.DOCKERHUB_USERNAME != null
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: env.DOCKERHUB_USERNAME != null
        run: make -e GIT_URL=$(git remote get-url origin) docker.buildx
